[config]
schemaVersion = "0.0.1"

[package]
namespace = "Conductor"
name = "Conductor"
versionNumber = "0.3.1"
description = "Central library of reusable custom effects, status effects, and keywords to make modding Monster Train 2 safer and easier, used as a dependency for other mods."
websiteUrl = "https://github.com/Monster-Train-2-Modding-Group/Conductor"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.6.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


